//! The characters the quick menu offers, and how they are searched.
//!
//! Both tables are generated by `data/quick/generate.py` from the Unicode and
//! CLDR sources and embedded whole, so the menu works offline and opens without
//! reading anything from disk. They are parsed on first use: the emoji table
//! when the Emoji tab is shown, the full name table only once a symbol search
//! reaches past the curated categories or a name is needed.

use std::{
    collections::{HashMap, HashSet},
    sync::OnceLock,
};

const EMOJI_TSV: &str = include_str!("../../data/quick/emoji.tsv");
const UNICODE_TSV: &str = include_str!("../../data/quick/unicode.tsv");

/// Most results a search shows. Past this the grid only gets harder to scan.
pub const SEARCH_LIMIT: usize = 400;

/// The five Fitzpatrick modifiers, lightest first. Index `0` in the picker is
/// "no modifier", so tone `n` is `SKIN_TONES[n - 1]`.
pub const SKIN_TONES: [char; 5] = [
    '\u{1F3FB}',
    '\u{1F3FC}',
    '\u{1F3FD}',
    '\u{1F3FE}',
    '\u{1F3FF}',
];
const VS16: char = '\u{FE0F}';

/// One cell in the grid.
#[derive(Clone, Debug, PartialEq)]
pub struct Item {
    /// What is shown, and what is inserted.
    pub text: String,
    /// A human name for the footer.
    pub name: String,
}

// -- Emoji -----------------------------------------------------------------

#[derive(Clone, Copy, Debug)]
pub struct Emoji {
    pub group: &'static str,
    pub glyph: &'static str,
    /// Emoji version it was introduced in, as `(major, minor)`.
    pub version: (u8, u8),
    /// Whether it takes a skin-tone modifier after its first code point.
    pub tones: bool,
    pub name: &'static str,
    pub keywords: &'static str,
}

impl Emoji {
    /// The glyph in skin tone `tone` (`0` for none), when it has tones.
    pub fn toned(&self, tone: u8) -> String {
        match (self.tones, tone) {
            (true, 1..=5) => with_tone(self.glyph, SKIN_TONES[usize::from(tone) - 1]),
            _ => self.glyph.to_string(),
        }
    }

    /// A lone code point, optionally followed by the emoji selector — the
    /// kind whose support a font can be asked about reliably.
    pub fn is_single(&self) -> bool {
        let mut chars = self.glyph.chars();
        chars.next().is_some()
            && match chars.next() {
                None => true,
                Some(VS16) => chars.next().is_none(),
                Some(_) => false,
            }
    }

    fn item(&self, tone: u8) -> Item {
        Item {
            text: self.toned(tone),
            name: capitalise(self.name),
        }
    }
}

/// The modifier follows the first code point, replacing an emoji-presentation
/// selector there — the rule the generator checked every toned emoji against.
fn with_tone(glyph: &str, tone: char) -> String {
    let mut chars = glyph.chars();
    let mut toned = String::with_capacity(glyph.len() + 4);
    if let Some(first) = chars.next() {
        toned.push(first);
        toned.push(tone);
    }
    let rest = chars.as_str();
    toned.push_str(rest.strip_prefix(VS16).unwrap_or(rest));
    toned
}

/// Undoes [`with_tone`] closely enough to find the base emoji again: drops the
/// modifiers, so `👍🏽` looks up as `👍`.
fn strip_tones(text: &str) -> String {
    text.chars().filter(|ch| !SKIN_TONES.contains(ch)).collect()
}

pub struct EmojiTable {
    pub emoji: Vec<Emoji>,
    /// Group names in table order, which is the order Unicode presents them.
    pub groups: Vec<&'static str>,
    by_glyph: HashMap<&'static str, usize>,
}

impl EmojiTable {
    fn parse(tsv: &'static str) -> Self {
        let mut emoji = Vec::new();
        let mut groups: Vec<&'static str> = Vec::new();
        for line in tsv.lines() {
            let mut fields = line.split('\t');
            let (Some(group), Some(_subgroup), Some(glyph), Some(version), Some(tones), Some(name)) = (
                fields.next(),
                fields.next(),
                fields.next(),
                fields.next(),
                fields.next(),
                fields.next(),
            ) else {
                continue;
            };
            if groups.last() != Some(&group) {
                groups.push(group);
            }
            emoji.push(Emoji {
                group,
                glyph,
                version: parse_version(version),
                tones: tones == "1",
                name,
                keywords: fields.next().unwrap_or(""),
            });
        }
        let by_glyph = emoji
            .iter()
            .enumerate()
            .map(|(index, emoji)| (emoji.glyph, index))
            .collect();
        Self {
            emoji,
            groups,
            by_glyph,
        }
    }

    /// The emoji `text` is, in any skin tone.
    pub fn find(&self, text: &str) -> Option<&Emoji> {
        self.by_glyph
            .get(text)
            .or_else(|| self.by_glyph.get(strip_tones(text).as_str()))
            .or_else(|| {
                // A toned emoji loses its selector along with the tone.
                let mut base = strip_tones(text);
                let first = base.chars().next()?;
                base.insert(first.len_utf8(), VS16);
                self.by_glyph.get(base.as_str())
            })
            .map(|&index| &self.emoji[index])
    }

    pub fn group_items(
        &self,
        group: &str,
        tone: u8,
        supported: impl Fn(&Emoji) -> bool,
    ) -> Vec<Item> {
        self.emoji
            .iter()
            .filter(|emoji| emoji.group == group && supported(emoji))
            .map(|emoji| emoji.item(tone))
            .collect()
    }

    pub fn search(&self, query: &str, tone: u8, supported: impl Fn(&Emoji) -> bool) -> Vec<Item> {
        let query = Query::new(query);
        if query.is_empty() {
            return Vec::new();
        }
        let mut ranked: Vec<(u8, usize, &Emoji)> = self
            .emoji
            .iter()
            .filter(|emoji| supported(emoji))
            .filter_map(|emoji| {
                query
                    .rank(emoji.name, emoji.keywords)
                    .map(|rank| (rank, emoji.name.len(), emoji))
            })
            .collect();
        // Stable, so equally good matches keep Unicode's order.
        ranked.sort_by_key(|(rank, length, _)| (*rank, *length));
        ranked
            .into_iter()
            .take(SEARCH_LIMIT)
            .map(|(_, _, emoji)| emoji.item(tone))
            .collect()
    }

    /// Emoji versions in the table, oldest first, each with its lone-code-point
    /// emoji — what a font's support for that version is judged by.
    pub fn versions(&self) -> Vec<((u8, u8), Vec<&Emoji>)> {
        let mut versions: Vec<((u8, u8), Vec<&Emoji>)> = Vec::new();
        for emoji in &self.emoji {
            match versions
                .iter_mut()
                .find(|(version, _)| *version == emoji.version)
            {
                Some((_, members)) => members.push(emoji),
                None => versions.push((emoji.version, vec![emoji])),
            }
        }
        for (_, members) in &mut versions {
            members.retain(|emoji| emoji.is_single());
        }
        versions.sort_by_key(|(version, _)| *version);
        versions
    }
}

fn parse_version(version: &str) -> (u8, u8) {
    let mut parts = version.split('.').map(|part| part.parse().unwrap_or(0));
    (parts.next().unwrap_or(0), parts.next().unwrap_or(0))
}

pub fn emoji() -> &'static EmojiTable {
    static TABLE: OnceLock<EmojiTable> = OnceLock::new();
    TABLE.get_or_init(|| EmojiTable::parse(EMOJI_TSV))
}

/// A short icon for each Unicode emoji group, for the category bar.
pub fn emoji_group_icon(group: &str) -> &'static str {
    match group {
        "Smileys & Emotion" => "😀",
        "People & Body" => "👋",
        "Animals & Nature" => "🐻",
        "Food & Drink" => "🍔",
        "Travel & Places" => "🚗",
        "Activities" => "⚽",
        "Objects" => "💡",
        "Symbols" => "🔣",
        "Flags" => "🏁",
        _ => "❔",
    }
}

// -- Unicode names ---------------------------------------------------------

#[derive(Clone, Copy, Debug)]
pub struct Named {
    pub code: u32,
    pub name: &'static str,
    pub keywords: &'static str,
}

impl Named {
    fn item(&self) -> Option<Item> {
        Some(Item {
            text: char::from_u32(self.code)?.to_string(),
            name: capitalise(&self.name.to_lowercase()),
        })
    }
}

pub struct UnicodeTable {
    /// Sorted by code point, as the source is.
    entries: Vec<Named>,
}

impl UnicodeTable {
    fn parse(tsv: &'static str) -> Self {
        let entries = tsv
            .lines()
            .filter_map(|line| {
                let mut fields = line.split('\t');
                let code = u32::from_str_radix(fields.next()?, 16).ok()?;
                let name = fields.next()?;
                Some(Named {
                    code,
                    name,
                    keywords: fields.next().unwrap_or(""),
                })
            })
            .collect();
        Self { entries }
    }

    pub fn get(&self, code: u32) -> Option<&Named> {
        self.entries
            .binary_search_by_key(&code, |named| named.code)
            .ok()
            .map(|index| &self.entries[index])
    }

    fn search(&self, query: &Query) -> Vec<(u8, &Named)> {
        let mut ranked: Vec<(u8, usize, &Named)> = self
            .entries
            .iter()
            .filter_map(|named| {
                query
                    .rank(named.name, named.keywords)
                    .map(|rank| (rank, named.name.len(), named))
            })
            .collect();
        ranked.sort_by_key(|(rank, length, _)| (*rank, *length));
        ranked
            .into_iter()
            .map(|(rank, _, named)| (rank, named))
            .collect()
    }
}

pub fn unicode() -> &'static UnicodeTable {
    static TABLE: OnceLock<UnicodeTable> = OnceLock::new();
    TABLE.get_or_init(|| UnicodeTable::parse(UNICODE_TSV))
}

// -- Symbols ---------------------------------------------------------------

enum Span {
    Chars(&'static str),
    Range(u32, u32),
}

pub struct SymbolCategory {
    pub name: &'static str,
    pub icon: &'static str,
    spans: &'static [Span],
}

impl SymbolCategory {
    fn chars(&self) -> impl Iterator<Item = char> + '_ {
        self.spans
            .iter()
            .flat_map(|span| -> Box<dyn Iterator<Item = char>> {
                match span {
                    Span::Chars(chars) => Box::new(chars.chars()),
                    Span::Range(start, end) => Box::new((*start..=*end).filter_map(char::from_u32)),
                }
            })
    }

    /// Every assigned character in the category, named. Ranges may cross
    /// unassigned code points; those have no name and are left out.
    pub fn items(&self) -> Vec<Item> {
        let table = unicode();
        let mut seen = Vec::new();
        self.chars()
            .filter(|ch| {
                let fresh = !seen.contains(ch);
                seen.push(*ch);
                fresh
            })
            .filter_map(|ch| table.get(u32::from(ch))?.item())
            .collect()
    }
}

/// The Symbols tab's categories, in the order the category bar shows them.
pub const SYMBOL_CATEGORIES: &[SymbolCategory] = &[
    SymbolCategory {
        name: "Punctuation",
        icon: "§",
        spans: &[Span::Chars(
            "“”‘’«»‹›„‚—–‐‑…·•‣◦⁃¶§†‡‰‱′″‴¡¿‼⁇⁈⁉‽⸮※⁂⁎⁑¦¨´`ˆ˜¯¸©®™℠℗№℮°℃℉µ¤ªº",
        )],
    },
    SymbolCategory {
        name: "Currency",
        icon: "€",
        spans: &[
            Span::Chars("$¢£¥€"),
            Span::Range(0x20A0, 0x20C0),
            Span::Chars("﷼"),
        ],
    },
    SymbolCategory {
        name: "Math",
        icon: "∑",
        spans: &[
            Span::Chars(
                "±∓×÷−∕⋅∘√∛∜∞∝∑∏∐∫∬∭∮∂∆∇≈≉≠≡≢≤≥≦≧≪≫≺≻∼≃≅∈∉∋∌⊂⊃⊄⊅⊆⊇∪∩∅∀∃∄¬∧∨⊻⊕⊖⊗⊘⊙⊥∥∦∠∡∢⊾∴∵∶∷ℕℤℚℝℂℙℍℵℶℏ℘ℑℜ",
            ),
            Span::Chars("½⅓⅔¼¾⅕⅖⅗⅘⅙⅚⅐⅛⅜⅝⅞⅑⅒↉"),
            Span::Chars("⁰¹²³⁴⁵⁶⁷⁸⁹⁺⁻⁼⁽⁾ⁱⁿ₀₁₂₃₄₅₆₇₈₉₊₋₌₍₎"),
        ],
    },
    SymbolCategory {
        name: "Arrows",
        icon: "→",
        spans: &[
            Span::Range(0x2190, 0x21FF),
            Span::Chars("⟵⟶⟷⟸⟹⟺⟻⟼⟽⟾⤴⤵⤶⤷➔➘➙➚➛➜➝➞➟➠➡⬅⬆⬇⬈⬉⬊⬋⬌⬍"),
        ],
    },
    SymbolCategory {
        name: "Latin",
        icon: "é",
        spans: &[
            Span::Range(0x00C0, 0x00D6),
            Span::Range(0x00D8, 0x00F6),
            Span::Range(0x00F8, 0x017F),
            Span::Chars("ẞƏəȘșȚț"),
        ],
    },
    SymbolCategory {
        name: "Greek",
        icon: "Ω",
        spans: &[
            Span::Range(0x0391, 0x03A1),
            Span::Range(0x03A3, 0x03A9),
            Span::Range(0x03B1, 0x03C9),
            Span::Chars("ϑϕϖϰϱϵ"),
        ],
    },
    SymbolCategory {
        name: "Shapes",
        icon: "■",
        spans: &[Span::Range(0x25A0, 0x25FF), Span::Chars("⬛⬜⬟⬠⬡⬢⬣⬤⭐⭑⭒⭓⭔")],
    },
    SymbolCategory {
        name: "Box drawing",
        icon: "┼",
        spans: &[Span::Range(0x2500, 0x259F)],
    },
    SymbolCategory {
        name: "Technical",
        icon: "⌘",
        spans: &[Span::Chars(
            "⌘⌥⇧⌃⎋⏎↵⌫⌦⇥⇤⏏⌨⏻⏼⏽⭘⏾⎈⌂⌖⌗⌚⌛⏰⏱⏲⏳⏴⏵⏶⏷⏸⏹⏺⏩⏪⏫⏬⏭⏮⏯☰☱☲☳☴☵☶☷⋮⋯⋰⋱⌈⌉⌊⌋⌜⌝⌞⌟⌠⌡⎛⎜⎝⎞⎟⎠⎡⎢⎣⎤⎥⎦⎧⎨⎩⎪⎫⎬⎭",
        )],
    },
    SymbolCategory {
        name: "Miscellaneous",
        icon: "★",
        spans: &[
            Span::Chars("✓✔✗✘✕✖☐☑☒★☆✦✧✩✪✫✬✭✮✯✰❖✱✲✳✴✵✶✷✸✹❂❄❅❆❋"),
            Span::Chars(
                "♠♣♥♦♤♧♡♢♩♪♫♬♭♮♯☀☁☂☃☄☎☏☔☕☘☙☚☛☜☝☞☟☠☢☣☤☥☦☧☨☩☪☫☬☭☮☯☸☹☺☻☼☽☾♀♂⚢⚣⚤⚥⚦⚧⚠⚡⚐⚑⚒⚓⚔⚖⚗⚘⚙⚛⚜♻♼♽❤❥❦❧",
            ),
        ],
    },
];

/// Symbol search over all of Unicode by name, with the curated categories
/// first among equally good matches, since they hold what is usually wanted. A query that *is* a
/// character, or spells one as `U+2192` or `2192`, finds it directly.
pub fn search_symbols(query: &str) -> Vec<Item> {
    let table = unicode();
    let mut results: Vec<Item> = Vec::new();
    let mut seen: Vec<u32> = Vec::new();

    if let Some(code) = code_point(query.trim())
        && let Some(item) = table.get(code).and_then(Named::item)
    {
        seen.push(code);
        results.push(item);
    }
    let parsed = Query::new(query);
    if parsed.is_empty() {
        return results;
    }

    let curated: HashSet<u32> = SYMBOL_CATEGORIES
        .iter()
        .flat_map(SymbolCategory::chars)
        .map(u32::from)
        .collect();
    let mut matches = table.search(&parsed);
    // Unicode names are long and literal, so a name that happens to start
    // with the query ("RIGHT ARROW WITH SMALL CIRCLE") is no better a match
    // than one holding every word ("RIGHTWARDS ARROW"), or one with the query
    // as a keyword: those ranks are one tier, ordered curated first and then
    // shortest. An exact name elsewhere in Unicode still beats a curated
    // character that merely shares the start of a keyword.
    matches.sort_by_key(|(rank, named)| {
        let tier = match rank {
            0 => 0,
            1..=3 => 1,
            _ => 2,
        };
        (tier, !curated.contains(&named.code), named.name.len())
    });

    for (_, named) in matches {
        if results.len() >= SEARCH_LIMIT {
            break;
        }
        if seen.contains(&named.code) {
            continue;
        }
        seen.push(named.code);
        results.extend(named.item());
    }
    results
}

/// `→`, `U+2192`, `u2192` or `0x2192`. A bare hex word only counts with at
/// least four digits, so a search for "face" or "add" is not taken for one.
fn code_point(query: &str) -> Option<u32> {
    let mut chars = query.chars();
    if let (Some(ch), None) = (chars.next(), chars.next())
        && !ch.is_ascii_alphanumeric()
    {
        return Some(u32::from(ch));
    }
    let lower = query.to_ascii_lowercase();
    let (hex, prefixed) = match ["u+", "0x", "u"]
        .iter()
        .find_map(|prefix| lower.strip_prefix(prefix))
    {
        Some(hex) => (hex, true),
        None => (lower.as_str(), false),
    };
    let plausible = (1..=6).contains(&hex.len()) && (prefixed || hex.len() >= 4);
    if !plausible || !hex.chars().all(|ch| ch.is_ascii_hexdigit()) {
        return None;
    }
    // A hex-looking word ("cafe", "beef") is still more likely a word.
    if !prefixed && hex.chars().all(|ch| ch.is_ascii_alphabetic()) {
        return None;
    }
    u32::from_str_radix(hex, 16).ok()
}

// -- Matching --------------------------------------------------------------

/// A search, split into words that each have to start a word of the name or
/// the keywords.
struct Query {
    whole: String,
    words: Vec<String>,
}

impl Query {
    fn new(query: &str) -> Self {
        let whole = query.trim().to_lowercase();
        let words = split_words(&whole).map(str::to_string).collect();
        Self { whole, words }
    }

    fn is_empty(&self) -> bool {
        self.words.is_empty()
    }

    /// Lower is better; `None` is no match.
    ///
    /// 0 the name is the query, 1 the query is one of the keywords, 2 the name
    /// starts with it, 3 every word starts a word of the name, 4 every word
    /// starts a word of the name or keywords.
    ///
    /// A keyword said in full beats a name that merely starts the same way:
    /// "lol" is 😂's keyword, and only the start of "lollipop".
    fn rank(&self, name: &str, keywords: &str) -> Option<u8> {
        if name.eq_ignore_ascii_case(&self.whole) {
            return Some(0);
        }
        if split_words(keywords).any(|keyword| keyword.eq_ignore_ascii_case(&self.whole)) {
            return Some(1);
        }
        if starts_with_ignore_case(name, &self.whole) {
            return Some(2);
        }
        let in_name = |word: &String| {
            split_words(name).any(|candidate| starts_with_ignore_case(candidate, word))
        };
        if self.words.iter().all(in_name) {
            return Some(3);
        }
        let anywhere = |word: &String| {
            in_name(word)
                || split_words(keywords).any(|candidate| starts_with_ignore_case(candidate, word))
        };
        self.words.iter().all(anywhere).then_some(4)
    }
}

fn split_words(text: &str) -> impl Iterator<Item = &str> {
    text.split(|ch: char| !ch.is_alphanumeric())
        .filter(|word| !word.is_empty())
}

/// ASCII case folding is enough: Unicode names are uppercase ASCII, and the
/// emoji names are lowercase already.
fn starts_with_ignore_case(text: &str, prefix: &str) -> bool {
    text.len() >= prefix.len()
        && text.is_char_boundary(prefix.len())
        && text[..prefix.len()].eq_ignore_ascii_case(prefix)
}

fn capitalise(text: &str) -> String {
    let mut chars = text.chars();
    match chars.next() {
        Some(first) => first.to_uppercase().chain(chars).collect(),
        None => String::new(),
    }
}

/// The footer name of any text the menu may have inserted before: an emoji in
/// any tone, or a single character.
pub fn name_of(text: &str) -> String {
    if let Some(emoji) = emoji().find(text) {
        return capitalise(emoji.name);
    }
    let mut chars = text.chars();
    match (chars.next(), chars.next()) {
        (Some(ch), None) => unicode()
            .get(u32::from(ch))
            .and_then(Named::item)
            .map(|item| item.name)
            .unwrap_or_default(),
        _ => String::new(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_tables_parse_whole() {
        let table = emoji();
        assert!(table.emoji.len() > 1500);
        assert_eq!(table.groups.first(), Some(&"Smileys & Emotion"));
        assert!(table.groups.contains(&"Flags"));
        assert!(!table.groups.contains(&"Component"));
        assert_eq!(
            unicode().get(0x2192).map(|named| named.name),
            Some("RIGHTWARDS ARROW")
        );
    }

    #[test]
    fn every_group_has_an_icon() {
        for group in &emoji().groups {
            assert_ne!(emoji_group_icon(group), "❔", "{group}");
        }
    }

    #[test]
    fn skin_tones_apply_and_are_found_again() {
        let table = emoji();
        let thumbs = table.find("👍").expect("thumbs up");
        assert!(thumbs.tones);
        assert_eq!(thumbs.toned(3), "👍🏽");
        assert_eq!(thumbs.toned(0), "👍");

        // The selector after the first code point makes way for the tone.
        let hand = table.find("🖐️").expect("hand with fingers splayed");
        assert_eq!(hand.toned(1), "🖐🏻");
        assert_eq!(table.find("🖐🏻").map(|emoji| emoji.glyph), Some(hand.glyph));

        let grinning = table.find("😀").expect("grinning face");
        assert!(!grinning.tones);
        assert_eq!(grinning.toned(4), "😀");
    }

    #[test]
    fn emoji_search_uses_names_and_keywords() {
        let results = emoji().search("lol", 0, |_| true);
        assert_ne!(results[0].text, "🍭", "a keyword said in full comes first");
        assert!(results.iter().any(|item| item.text == "😂"));

        let results = emoji().search("thumbs up", 2, |_| true);
        assert_eq!(results.first().map(|item| item.text.as_str()), Some("👍🏼"));
        assert_eq!(results[0].name, "Thumbs up");

        assert!(emoji().search("   ", 0, |_| true).is_empty());
        assert!(emoji().search("zzqqxx", 0, |_| true).is_empty());
    }

    #[test]
    fn symbol_search_favours_the_curated_set() {
        let results = search_symbols("right arrow");
        let first = results.first().expect("a match");
        assert_eq!(first.text, "→");
        assert_eq!(first.name, "Rightwards arrow");

        // Beyond the curated categories.
        assert!(
            search_symbols("snowman")
                .iter()
                .any(|item| item.text == "☃")
        );
        assert!(
            search_symbols("hiragana letter a")
                .iter()
                .any(|item| item.text == "あ")
        );
    }

    #[test]
    fn a_code_point_is_found_directly() {
        assert_eq!(search_symbols("U+2192")[0].text, "→");
        assert_eq!(search_symbols("2192")[0].text, "→");
        assert_eq!(search_symbols("→")[0].text, "→");
        assert_eq!(code_point("face"), None);
        assert_eq!(code_point("add"), None);
        assert_eq!(code_point("12"), None);
        assert_eq!(code_point("u+41"), Some(0x41));
    }

    #[test]
    fn ranking_prefers_whole_then_prefix_then_words() {
        let query = Query::new("heart");
        assert_eq!(query.rank("heart", ""), Some(0));
        assert_eq!(query.rank("heart suit", ""), Some(2));
        assert_eq!(query.rank("black heart suit", ""), Some(3));
        assert_eq!(query.rank("red suit", "heartfelt love"), Some(4));
        assert_eq!(query.rank("red suit", "love heart"), Some(1));
        assert_eq!(query.rank("red suit", "love"), None);
    }

    #[test]
    fn categories_hold_only_named_characters() {
        for category in SYMBOL_CATEGORIES {
            let items = category.items();
            assert!(!items.is_empty(), "{}", category.name);
            assert!(
                items.iter().all(|item| !item.name.is_empty()),
                "{}",
                category.name
            );
        }
        let currency = SYMBOL_CATEGORIES[1].items();
        assert!(currency.iter().any(|item| item.text == "€"));
        assert!(currency.iter().any(|item| item.text == "₿"));
    }

    #[test]
    fn names_are_found_for_recent_items() {
        assert_eq!(name_of("→"), "Rightwards arrow");
        assert_eq!(name_of("👍🏿"), "Thumbs up");
        assert_eq!(name_of("ab"), "");
    }

    #[test]
    fn versions_list_lone_code_points_only() {
        let versions = emoji().versions();
        assert!(versions.windows(2).all(|pair| pair[0].0 < pair[1].0));
        for (_, members) in &versions {
            assert!(members.iter().all(|emoji| emoji.is_single()));
        }
    }
}
